# Generated by Django 3.2.dev20201110203713 on 2020-11-24 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='known_assassin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.SET(''), related_name='player_known_assassin', to='ssa.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='target',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssa.player'),
        ),
    ]
