# Generated by Django 3.2.dev20201110203713 on 2020-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0002_auto_20201123_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
