# Generated by Django 3.2.dev20201110203713 on 2020-11-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0002_alter_player_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='target',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssa.player'),
        ),
    ]
