# Generated by Django 3.2.dev20201110203713 on 2020-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_handle'),
        ('ssa', '0003_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='profiles',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default='Pending', max_length=24),
        ),
    ]
