# Generated by Django 3.2.dev20201110203713 on 2020-11-25 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssa', '0004_auto_20201125_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='profiles',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
