# Generated by Django 3.2.dev20201110203713 on 2020-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0005_auto_20201125_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
